title: ANewShaman
description: Notes on machine learning, and whatever else I'm digging into. Weirdly philosophical at times, but mostly just a place to dump my thoughts and ideas.
theme: minima

show_excerpts: true


plugins:
  - jekyll-feed

markdown: kramdown